$(document).ready(function(){
    $("#startButton").click(function(){
    $("#scene1").fadeIn(2000);
    $("#begin").hide();
    $("#title").hide();
    $("#startButton").hide();
  });
  $("#firstLeft").click(function(){
    $("#scene1").hide();
    $("#firstDeath").fadeIn(2000);
  });
  $("#firstRight").click(function(){
    $("#scene1").hide();
    $("#scene2").fadeIn(2000);
  });
  $("#secondLeft").click(function(){
    $("#scene2").hide();
    $("#scene3").fadeIn(2000);
  });
  $("#secondRight").click(function(){
    $("#scene2").hide();
    $("#secondDeath").fadeIn(2000);
  });
  $("#thirdDoors").click(function(){
    $("#scene3").hide();
    $("#thirdDeath").fadeIn(2000);
  });
  $("#thirdStraight").click(function(){
    $("#scene3").hide();
    $("#scene4").fadeIn(2000);
  });
  $("#fourthMain").click(function(){
    $("#scene4").hide();  
    $("#fourthDeath").fadeIn(2000);
  });
  $("#fourthBack").click(function(){
    $("#scene4").hide();
    $("#scene5").fadeIn(2000);
  });
  $("#tryAgain1").click(function(){
    $("#firstDeath").hide();
    $("#scene1").fadeIn(1000);
  });
  $("#tryAgain2").click(function(){
    $("#secondDeath").hide();
    $("#scene2").fadeIn(1000);
  });
  $("#tryAgain3").click(function(){
    $("#thirdDeath").hide();
    $("#scene3").fadeIn(1000);
  });
  $("#tryAgain4").click(function(){
    $("#fourthDeath").hide();
    $("#scene4").fadeIn(1000);
  });
});